<?php
/**
 * DocumentDataDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * test
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentDataDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description DocumentDataDto
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentDataDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DocumentDataDto"
     */
    public function testDocumentDataDto()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "protocol_number"
     */
    public function testPropertyProtocolNumber()
    {

    }

    /**
     * Test attribute "protocol_date"
     */
    public function testPropertyProtocolDate()
    {

    }

    /**
     * Test attribute "doc_type"
     */
    public function testPropertyDocType()
    {

    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {

    }

    /**
     * Test attribute "sender_protocol"
     */
    public function testPropertySenderProtocol()
    {

    }

    /**
     * Test attribute "sender_date_protocol"
     */
    public function testPropertySenderDateProtocol()
    {

    }

    /**
     * Test attribute "doc_category"
     */
    public function testPropertyDocCategory()
    {

    }

    /**
     * Test attribute "theme"
     */
    public function testPropertyTheme()
    {

    }

    /**
     * Test attribute "ada"
     */
    public function testPropertyAda()
    {

    }

    /**
     * Test attribute "attached_docs_descr"
     */
    public function testPropertyAttachedDocsDescr()
    {

    }

    /**
     * Test attribute "director"
     */
    public function testPropertyDirector()
    {

    }

    /**
     * Test attribute "attached_id"
     */
    public function testPropertyAttachedId()
    {

    }

}
